export const PAGINATION_SIZE = 12;
export const DEFAULT_GRID_IMG_LOAD_EAGER_COUNT = 3;
export const ATTR_LOADING_EAGER = 'eager';
export const ATTR_LOADING_LAZY = 'lazy';
export function getImageLoadingPriority(
  index: number,
  maxEagerLoadCount = DEFAULT_GRID_IMG_LOAD_EAGER_COUNT,
) {
  return index < maxEagerLoadCount ? ATTR_LOADING_EAGER : undefined;
}

export const HYGRAPH_CACHE_NAME = 'hygraph';
export const KLAVIYO_BASE_URL = 'https://a.klaviyo.com';
export const KLAVIYO_COMPANY_ID = 'RDT3xD';

export const EMAILJS_CONTACT_TEMPLATE_ID = 'template_0jee2h8';
export const EMAILJS_APPOINTMENT_TEMPLATE_ID = 'template_q2yw635';
export const EMAILJS_SERVICE_ID = 'service_q8ej60l';

export const EMAILJS_PUBKEY = 'hi4FCFs4Sq1Wj6URH';

export const SEO_PLACEHOLDER = {
  title: 'No Maintenance',
  titleTemplate: '%s',
  description: 'No Maintenance is a brand based in Los Angeles, California. ',
  handle: '@shopify',
  url: 'https://nomaintenance.us',
  robots: {
    noIndex: false,
    noFollow: false,
  },
  jsonLd: {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'No Maintenance',
    logo: 'https://cdn.shopify.com/s/files/1/0422/9319/9005/files/Frame_8_b1dfc928-2421-43e2-be8f-b34929752f5d.png?v=1694719336',
    sameAs: [
      'https://twitter.com/shopify',
      'https://facebook.com/shopify',
      'https://instagram.com/shopify',
      'https://youtube.com/shopify',
      'https://tiktok.com/@shopify',
    ],
    url: 'https://nomaintenance.us/',
    potentialAction: {
      '@type': 'SearchAction',
      target: 'https://nomaintenance.us/search?q={search_term}',
      query: "required name='search_term'",
    },
  },
};

export const GOOGLE_TLDS = [
  'https://*.google.com',
  'https://*.google.ad',
  'https://*.google.ae',
  'https://*.google.com.af',
  'https://*.google.com.ag',
  'https://*.google.al',
  'https://*.google.am',
  'https://*.google.co.ao',
  'https://*.google.com.ar',
  'https://*.google.as',
  'https://*.google.at',
  'https://*.google.com.au',
  'https://*.google.az',
  'https://*.google.ba',
  'https://*.google.com.bd',
  'https://*.google.be',
  'https://*.google.bf',
  'https://*.google.bg',
  'https://*.google.com.bh',
  'https://*.google.bi',
  'https://*.google.bj',
  'https://*.google.com.bn',
  'https://*.google.com.bo',
  'https://*.google.com.br',
  'https://*.google.bs',
  'https://*.google.bt',
  'https://*.google.co.bw',
  'https://*.google.by',
  'https://*.google.com.bz',
  'https://*.google.ca',
  'https://*.google.cd',
  'https://*.google.cf',
  'https://*.google.cg',
  'https://*.google.ch',
  'https://*.google.ci',
  'https://*.google.co.ck',
  'https://*.google.cl',
  'https://*.google.cm',
  'https://*.google.cn',
  'https://*.google.com.co',
  'https://*.google.co.cr',
  'https://*.google.com.cu',
  'https://*.google.cv',
  'https://*.google.com.cy',
  'https://*.google.cz',
  'https://*.google.de',
  'https://*.google.dj',
  'https://*.google.dk',
  'https://*.google.dm',
  'https://*.google.com.do',
  'https://*.google.dz',
  'https://*.google.com.ec',
  'https://*.google.ee',
  'https://*.google.com.eg',
  'https://*.google.es',
  'https://*.google.com.et',
  'https://*.google.fi',
  'https://*.google.com.fj',
  'https://*.google.fm',
  'https://*.google.fr',
  'https://*.google.ga',
  'https://*.google.ge',
  'https://*.google.gg',
  'https://*.google.com.gh',
  'https://*.google.com.gi',
  'https://*.google.gl',
  'https://*.google.gm',
  'https://*.google.gr',
  'https://*.google.com.gt',
  'https://*.google.gy',
  'https://*.google.com.hk',
  'https://*.google.hn',
  'https://*.google.hr',
  'https://*.google.ht',
  'https://*.google.hu',
  'https://*.google.co.id',
  'https://*.google.ie',
  'https://*.google.co.il',
  'https://*.google.im',
  'https://*.google.co.in',
  'https://*.google.iq',
  'https://*.google.is',
  'https://*.google.it',
  'https://*.google.je',
  'https://*.google.com.jm',
  'https://*.google.jo',
  'https://*.google.co.jp',
  'https://*.google.co.ke',
  'https://*.google.com.kh',
  'https://*.google.ki',
  'https://*.google.kg',
  'https://*.google.co.kr',
  'https://*.google.com.kw',
  'https://*.google.kz',
  'https://*.google.la',
  'https://*.google.com.lb',
  'https://*.google.li',
  'https://*.google.lk',
  'https://*.google.co.ls',
  'https://*.google.lt',
  'https://*.google.lu',
  'https://*.google.lv',
  'https://*.google.com.ly',
  'https://*.google.co.ma',
  'https://*.google.md',
  'https://*.google.me',
  'https://*.google.mg',
  'https://*.google.mk',
  'https://*.google.ml',
  'https://*.google.com.mm',
  'https://*.google.mn',
  'https://*.google.com.mt',
  'https://*.google.mu',
  'https://*.google.mv',
  'https://*.google.mw',
  'https://*.google.com.mx',
  'https://*.google.com.my',
  'https://*.google.co.mz',
  'https://*.google.com.na',
  'https://*.google.com.ng',
  'https://*.google.com.ni',
  'https://*.google.ne',
  'https://*.google.nl',
  'https://*.google.no',
  'https://*.google.com.np',
  'https://*.google.nr',
  'https://*.google.nu',
  'https://*.google.co.nz',
  'https://*.google.com.om',
  'https://*.google.com.pa',
  'https://*.google.com.pe',
  'https://*.google.com.pg',
  'https://*.google.com.ph',
  'https://*.google.com.pk',
  'https://*.google.pl',
  'https://*.google.pn',
  'https://*.google.com.pr',
  'https://*.google.ps',
  'https://*.google.pt',
  'https://*.google.com.py',
  'https://*.google.com.qa',
  'https://*.google.ro',
  'https://*.google.ru',
  'https://*.google.rw',
  'https://*.google.com.sa',
  'https://*.google.com.sb',
  'https://*.google.sc',
  'https://*.google.se',
  'https://*.google.com.sg',
  'https://*.google.sh',
  'https://*.google.si',
  'https://*.google.sk',
  'https://*.google.com.sl',
  'https://*.google.sn',
  'https://*.google.so',
  'https://*.google.sm',
  'https://*.google.sr',
  'https://*.google.st',
  'https://*.google.com.sv',
  'https://*.google.td',
  'https://*.google.tg',
  'https://*.google.co.th',
  'https://*.google.com.tj',
  'https://*.google.tl',
  'https://*.google.tm',
  'https://*.google.tn',
  'https://*.google.to',
  'https://*.google.com.tr',
  'https://*.google.tt',
  'https://*.google.com.tw',
  'https://*.google.co.tz',
  'https://*.google.com.ua',
  'https://*.google.co.ug',
  'https://*.google.co.uk',
  'https://*.google.com.uy',
  'https://*.google.co.uz',
  'https://*.google.com.vc',
  'https://*.google.co.ve',
  'https://*.google.co.vi',
  'https://*.google.com.vn',
  'https://*.google.vu',
  'https://*.google.ws',
  'https://*.google.rs',
  'https://*.google.co.za',
  'https://*.google.co.zm',
  'https://*.google.co.zw',
  'https://*.google.cat',
];

export const CONV_ADDED_TO_CART = 1;
